### ISSUE TITLE
no repository field in the package.json

### ISSUE THREAD

**Issue by callumacrae** [Lostmyname/jester.theme.default#1]
npmjs.com isn't linking to github because of the missing website and repo fields

**Comment by urbanautomaton** [comment]
Adding this would also be really nice as it'd eliminate a spurious warning during deploys. :+1:

**Comment by urbanautomaton** [comment]
In fact most of the components lack a repo field:

```
npm WARN package.json lmn.jester.component.button@0.2.0 No repository field.
npm WARN package.json lmn-monkey@3.0.1 No repository field.
npm WARN package.json lmn.jester.component.button@0.5.1 No repository field.
npm WARN package.json lmn.jester.component.collapsible@0.4.0 No repository field.
npm WARN package.json lmn.jester.component.divider@0.4.2 No repository field.
npm WARN package.json lmn.jester.component.swiper@0.3.0 No repository field.
npm WARN package.json lmn.jester.component.tab@0.4.0 No repository field.
npm WARN package.json lmn.jester.component.video@0.4.0 No repository field.
npm WARN package.json lmn.jester.component.gallery@0.6.0 No repository field.
npm WARN package.json lmn.tarantula@0.5.1 No repository field.
npm WARN package.json lmn.jester.component.panel@0.2.1 No repository field.
npm WARN package.json lmn.jester.component.switch@0.3.0 No repository field.
npm WARN package.json lmn.jester.theme.default@0.12.5 No repository field.
npm WARN package.json lmn.jester.component.colour@0.2.3 No repository field.
```

If there are no objections I'll open some PRs while watching deploys fail. :)

**Comment by callumacrae** [comment]
@urbanautomaton `yes '' | npm init` will do it automatically if you clone from github and run it in the repo

**Comment by callumacrae** [comment]
`(yes '' | npm init) && git commit -am 'added repo' && git push origin master` resulted in ac3cd42679a1e5e654218e9c97fea391d90aaa7e, which looks okay

**Comment by urbanautomaton** [comment]
Nice one, thanks @callumacrae.

**Comment by urbanautomaton** [comment]
Is it all right for me to push straight to master for stuff like this btw, or should I open hotfix PRs?

**Comment by callumacrae** [comment]
In theory, pushing straight to master won't do anything until `npm version` and `npm publish` are run, so it's fine.
